Improve AndroidIDE
itsaky/AndroidIDE pull request #196
Opened 2022-05-23 18:22 UTC by MrIkso

Updated project templates similarly to Android Studio.
Added Kotlin Language highlighting
Added Cpp/C Language highlighting

2022-05-29 13:51 UTC, itsaky commented on app/src/main/java/com/itsaky/androidide/language/kotlin/KotlinAnalyzer.java
> +                    colors.addIfNeeded(line, column, SchemeAndroidIDE.COMMENT);
Us

2022-05-29 14:18 UTC, itsaky requested changes

2022-05-29 16:47 UTC, itsaky approved these changes

2022-05-29 21:22 UTC, aexarch commented
Can this be merged? :) need any testing? Just wondering since status is "approved". I often forget clicking merge after clicking approve on team projects, so I thought I'd leave this note here. :)

2022-05-30 01:41 UTC, merged

2022-05-30 01:42 UTC, itsaky commented
@MrIkso Thank you for your contributions!